---
baseURL: https://vadanx.dev/

enableEmoji: true

enableRobotsTXT: true

languageCode: en-us

markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    noClasses: true
    style: monokai

menu:
  main:
  - name: Gaming 🎲
    url: /gaming/
    weight: 10
  - name: Technology 🤖
    url: /technology/
    weight: 20
  - name: Tags 🏷️
    url: /tags/
    weight: 50

minify:
  disableXML: true
  minifyOutput: true

paginate: 5

params:
  assets:
    apple_touch_icon: favicon-180x180.png
    favicon: favicon.ico
    favicon16x16: favicon-16x16.png
    favicon32x32: favicon-32x32.png
  author: Andrew 
  defaultTheme: auto
  disableThemeToggle: false
  env: production
  label:
    icon: images/logo-35x35.png
    iconHeight: 35
    text: vadanx.dev
  profileMode:
    enabled: true
    subtitle: links
    imageUrl: images/logo-256x256.png
    imageTitle: The cat is a lie
    imageWidth: 256
    imageHeight: 256
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowReadingTime: true
  ShowRssButtonInSectionTermList: true
  ShowShareButtons: false
  socialIcons:
  - name: email
    url: mailto:andrew@vadanx.dev
  - name: github
    url: https://github.com/vadanx
  - name: linkedin
    url: https://www.linkedin.com/in/vadanx
  - name: reddit
    url: https://www.reddit.com/user/vadanx

theme: PaperMod

title: vadanx.dev
